---
- name: Manage swap file entry in fstab
  ansible.builtin.mount:
    name: none
    src: "{{ swap_file_path }}"
    fstype: swap
    opts: sw
    state: "{{ swap_file_state }}"


- name: Remove swapfile
  when: swap_file_state == "absent"
  block:
    - name: Disable swap
      ansible.builtin.shell:
        cmd: swapoff -a

    - name: Remove swapfile
      ansible.builtin.file:
        path: "{{ swap_file_path }}"
        state: absent

- name: Create swapfile 
  when: swap_file_state == "present"
  block:
    - name: "Create swapfile {{ swap_file_size_mb }}"
      register: swap_file_create

      ansible.builtin.shell:
        cmd: "dd if=/dev/zero of={{ swap_file_path }} bs=1M count={{ swap_file_size_mb }}"
    - name: Set permissions on swapfile
      ansible.builtin.file:
        path: "{{ swap_file_path }}"
        owner: root
        group: root
        mode: "0600"

    - name: Make swap with swapfile
      when: swap_file_create is changed
      register: mkswap_result
      ansible.builtin.shell:
        cmd: mkswap {{ swap_file_path }}

    - name: Enable swapon on swapfile
      when: mkswap_result is changed
      ansible.builtin.command:
        cmd: swapon {{ swap_file_path }}
