---
- name: Manage swap file entry in fstab
  ansible.builtin.mount:
    name: none
    src: "{{ swap_file_path }}"
    fstype: swap
    opts: sw
    state: "{{ swap_file_state }}"


- name: Remove swapfile
  when: swap_file_state == "absent"
  block:
    - name: Disable swap
      ansible.builtin.shell:
        cmd: swapoff -a

    - name: Remove swapfile
      ansible.builtin.file:
        path: "{{ swap_file_path }}"
        state: absent

- name: Create swapfile
  when: swap_file_state == "present"
  block:
    - name: Create swapfile
      ansible.builtin.shell:
        cmd: "{{ swap_file_create_command }} creates='{{ swap_file_path }}'"
      register: swap_file_create

    - name: Set permissions on swapfile
      ansible.builtin.file:
        path: "{{ swap_file_path }}"
        owner: root
        group: root
        mode: "0600"

    - name: Make swap with swapfile
      ansible.builtin.shell:
        cmd: mkswap {{ swap_file_path }}
      when: swap_file_create is changed
      register: mkswap_result

    - name: Enable swapon on swapfile
      ansible.builtin.command:
        cmd: swapon {{ swap_file_path }}
      when: mkswap_result is changed
